Repository seng499-company1/backend, pull requests merged in 2022-07, with the labels that each got.

#80 check if db connection is alive
  api/dbconn.py
Labels: sprint-3

#85 Zoe/admins endpoints
  .github/workflows/pylint.yml
  api/admin.py
  tests/api/test_admin.py
Labels: sprint-3

#88 Zoe/preferences post timestamps
  api/dbconn.py
  api/preference.py
  requirements.txt
Labels: bug, sprint-3

#90 Implement Login Endpoint
  api/app.py
  api/login.py
  database/init_data/admin.txt
  database/sql/z_init.sql
  demos/sprint3/demo.sh
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/LoginInput.yaml
  docs/openapi/components/schemas/LoginResponse.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/login/login.yaml
Labels: sprint-3

#93 Add semester off attribute to ProfessorAvailability
  api/preference.py
  database/sql/schema.sql
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
  docs/openapi/components/schemas/ProfessorPreferenceNoID.yaml
Labels: documentation, enhancement, sprint-3

#92 Allows POST, PUT, GET, and DELETE explicitly.
  api/app.py
Labels: sprint-3

#95 Static course data import
  database/init_data/algo_data/chem_101.json
  database/init_data/algo_data/econ_180.json
  database/init_data/algo_data/engr_110.json
  database/init_data/algo_data/engr_120.json
  database/init_data/algo_data/engr_130.json
  database/init_data/algo_data/engr_141.json
  database/init_data/algo_data/math_100.json
  database/init_data/algo_data/math_101.json
  database/init_data/algo_data/math_109.json
  database/init_data/algo_data/math_110.json
  database/init_data/algo_data/math_122.json
  database/init_data/algo_data/phys_110.json
  database/init_data/algo_data/phys_111.json
  database/init_data/algo_data/stat_260.json
  database/init_data/algo_data/static_courses.json
Labels: sprint-3

#94 Add endpoint to return list of professor pref entry times
  api/preference.py
  database/sql/schema.sql
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/CoursePreferenceWithTimestamp.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
Labels: documentation, enhancement, sprint-3

#98 Close db conn cursor after execute
  api/dbconn.py
  api/preference.py
Labels: bug, story ponts:1, sprint-4

#105 Update prof pref timestamp endpoint to include year param
  api/dbconn.py
  api/preference.py
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ArrayProfessorPreferenceTimes.yaml
  docs/openapi/components/schemas/ProfessorPreferenceTimes.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/professors/professors_preferences_times.yaml
Labels: documentation, enhancement, story ponts:1, sprint-4

#115 Fix spring_req attribute returning false for all courses
  api/course.py
  api/dbconn.py
Labels: bug, story ponts:1, sprint-4

#107 Annie/97 close db conn
  api/dbconn.py
Labels: bug, story ponts:1, sprint-4

#112 Update how we deal with cross origin requests
  api/app.py
  requirements.txt
Labels: sprint-4

#108 Annie/97 handle raised exceptions
  api/admin.py
  api/course.py
  api/preference.py
  api/professor.py
  api/schedule.py
Labels: enhancement, story ponts:1, sprint-4

#117 preference form reminder endpoint
  api/professor.py
  docs/openapi/bundled.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/professors/professors_{id}_remind.yaml.yaml
Labels: sprint-4

#124 Merge down changes to Deploy Branch
  .github/workflows/pylint.yml
  .gitignore
  Dockerfile
  api/README.md
  api/admin.py
  api/app.py
  api/course.py
  api/dbconn.py
  api/helper.py
  api/init_data/fall_static_courses.json
  api/init_data/historical_data.json
  api/init_data/previous_enrolment.json
  api/init_data/spring_static_courses.json
  api/init_data/summer_static_courses.json
  api/populate_prof_prefs/prof_pref_inputter.py
  api/preference.py
  api/professor.py
  api/schedule.py
  database/init_data/algo_data/chem_101.json
  database/init_data/algo_data/econ_180.json
  database/init_data/algo_data/engr_110.json
  database/init_data/algo_data/engr_120.json
  database/init_data/algo_data/engr_130.json
  database/init_data/algo_data/engr_141.json
  database/init_data/algo_data/math_100.json
  database/init_data/algo_data/math_101.json
  database/init_data/algo_data/math_109.json
  database/init_data/algo_data/math_110.json
  database/init_data/algo_data/math_122.json
  database/init_data/algo_data/phys_110.json
  database/init_data/algo_data/phys_111.json
  database/init_data/algo_data/stat_260.json
  database/init_data/algo_data/static_courses.json
  database/sql/schema.sql
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ArrayProfessorPreferenceTimes.yaml
  docs/openapi/components/schemas/CoursePreferenceWithTimestamp.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
  docs/openapi/components/schemas/ProfessorPreferenceTimes.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/professors/professors_preferences_times.yaml
  docs/openapi/paths/professors/professors_{id}_remind.yaml.yaml
  requirements.txt
Labels: DevOps, sprint-4

#123 Fix post pref endpoint giving 500 error
  api/populate_prof_prefs/prof_pref_inputter.py
  api/preference.py
Labels: bug, story ponts:1, sprint-4

#109 Annie/52 query by year
  api/preference.py
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ArrayProfessorPreference.yaml
  docs/openapi/components/schemas/ArrayProfessorPreferenceTimes.yaml
  docs/openapi/components/schemas/ProfessorPreferenceTimes.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/professors/professors_preferences_times_{year}.yaml
  docs/openapi/paths/professors/professors_preferences_{id}.yaml
  docs/openapi/paths/professors/professors_{id}_preferences.yaml
  docs/openapi/paths/professors/professors_{id}_preferences_{year}.yaml
Labels: documentation, enhancement, story points:2, sprint-4

#133 132 update post courses
  api/course.py
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/Course.yaml
  docs/openapi/components/schemas/CourseNoID.yaml
Labels: bug, documentation, sprint-4

#130 Add CSC355 and CSC460
  database/init_data/courses.txt
Labels: enhancement, help wanted, story ponts:1, sprint-4

#134 Revert "Add CSC355 and CSC460"
  database/init_data/courses.txt
Labels: bug, sprint-4

#140 Add CSC355 and CSC460
  database/init_data/courses.txt
Labels: bug, enhancement, story ponts:1, sprint-4

#136 Performance Test plan files and README update
  README.md
  tests/performance/Admin Scen.jmx
  tests/performance/Prof. Scen.jmx
Labels: documentation, story points: 5, DevOps, sprint-4

#138 Added way to check if a course is covered by a professor or not.
  api/populate_prof_prefs/prof_pref_inputter.py
Labels: sprint-4

#143 IDs are now strings.
  api/init_data/fall_static_courses.json
  api/init_data/spring_static_courses.json
  api/init_data/summer_static_courses.json
  requirements.txt
Labels: sprint-4

#131 Update SQL query to grab the latest preference entry for each prof
  api/helper.py
Labels: enhancement, story points:2

#152 Update c1algo2 version to 1.0.1
  api/schedule.py
  requirements.txt
Labels: bug, enhancement, story ponts:1

#154 Update docs for pref endpoints
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ArrayProfessorPreference.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
  docs/openapi/paths/professors/professors_preferences_{id}.yaml
  docs/openapi/paths/professors/professors_{id}_preferences.yaml
Labels: documentation, story ponts:1
