Repository seng499-company1/backend, pull requests merged in 2022-06, with the labels that each got.

#39 Owen/19 db login
  database/demo/login.py
  database/demo/requirements.txt
  database/sql/users.sql
  requirements.txt
Labels: sprint-1

#38 Update database schema
  database/sql/schema.sql
Labels: sprint-1

#44 Owen/43 implement prof endpoints
  .gitignore
  api/dbconn.py
  api/professor.py
  database/sql/users.sql
  demos/sprint1/demo.sh
  docker-compose.yml
Labels: sprint-1

#46 Add preferred time property schema
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/Algorithm/AlgProfessor.yaml
  docs/openapi/components/schemas/AvailabilityDict.yaml
  docs/openapi/components/schemas/PreferredTime.yaml
  docs/openapi/components/schemas/PreferredTimes.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
  docs/openapi/components/schemas/ProfessorPreferenceNoID.yaml
Labels: documentation, story ponts:1

#54 Annie/53 remove multi preferences
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/ArrayProfessorPreferences.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/professors/professors_{id}_preferences.yaml
  docs/openapi/paths/professors/professors_{id}_preferences_{preference_id}.yaml
Labels: documentation, story ponts:1, sprint-2

#62 Annie/60 create course pref schema
  docs/openapi/bundled.yaml
  docs/openapi/components/schemas/Algorithm/ArrayCoursePreference.yaml
  docs/openapi/components/schemas/Algorithm/CourseEnthusiasm.yaml
  docs/openapi/components/schemas/CoursePreference.yaml
  docs/openapi/components/schemas/CoursePreferenceWithTimestamp.yaml
  docs/openapi/components/schemas/ProfessorPreference.yaml
  docs/openapi/components/schemas/ProfessorPreferenceNoID.yaml
Labels: documentation, story points:2, sprint-2

#65 Owen/integrate with frontend
  api/app.py
Labels: sprint-2

#68 Populate DB with course and professor data
  database/Dockerfile
  database/init_data/courses.txt
  database/init_data/profs.txt
  database/sql/schema.sql
  database/sql/z_init.sql
  docker-compose.yml
Labels: sprint-2

#69 company specific schedule endpoint
  .github/workflows/pylint.yml
  Dockerfile
  api/app.py
  api/schedule.py
  docs/openapi/bundled.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/schedules/schedules_company_{company_num}.yaml
  requirements.txt
  tests/api/test_schedules.py
Labels: sprint-2

#70 Annie/52 prof pref endpoints
  api/dbconn.py
  api/preference.py
  api/professor.py
  database/sql/schema.sql
  tests/api/test_professor.py
Labels: story points:8, sprint-2

#72 Owen/58 schedule endpoint
  .github/workflows/pylint.yml
  Dockerfile
  api/app.py
  api/schedule.py
  database/Dockerfile
  database/init_data/courses.txt
  database/init_data/profs.txt
  database/sql/schema.sql
  database/sql/z_init.sql
  docker-compose.yml
  docs/openapi/bundled.yaml
  docs/openapi/openapi.yaml
  docs/openapi/paths/schedules/schedules_company_{company_num}.yaml
  requirements.txt
  tests/api/test_schedules.py
Labels: DevOps

#78 Deploy branch update
  .github/workflows/pylint.yml
  api/dbconn.py
  api/preference.py
  api/professor.py
  api/schedule.py
  database/sql/schema.sql
  requirements.txt
  tests/api/test_professor.py
Labels: CI/CD, DevOps
